on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Install bats
      run: |
        sudo apt install bats
    - name: Bats tests
      run: |
        cd wstrings && bats wstrings.bats
